//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebClient.HotelServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelServiceReference1.HotelsWebServiceSoap")]
    public interface HotelsWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insert(string ID, string Name, string Description, string No, string City, string Country, string mobile, string Email, string username, string password, string Image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertAsync(string ID, string Name, string Description, string No, string City, string Country, string mobile, string Email, string username, string password, string Image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCustomerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoCustomerID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCustomerID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoCustomerIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCustomerData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddCustomerData(string customerid, string fname, string lastname, string address, string gender, string bday, string mobile, string email, string uname, string pword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCustomerData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddCustomerDataAsync(string customerid, string fname, string lastname, string address, string gender, string bday, string mobile, string email, string uname, string pword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHotelData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getHotelData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHotelData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getHotelDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoRoomID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoRoomID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoRoomID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoRoomIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertRoom(string ID, string Type, string Size, int price, int quantity, string Image, string hotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertRoomAsync(string ID, string Type, string Size, int price, int quantity, string Image, string hotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelLoginData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HotelLoginData(string Username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelLoginData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HotelLoginDataAsync(string Username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/customerLoginData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string customerLoginData(string Username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/customerLoginData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> customerLoginDataAsync(string Username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoAdminID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoAdminID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoAdminID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoAdminIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddAdmin(string ID, string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddAdminAsync(string ID, string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminLoginData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AdminLoginData(string Username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminLoginData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AdminLoginDataAsync(string Username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FilterData(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FilterDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterRoomType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FilterRoomType(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterRoomType", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FilterRoomTypeAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoomDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RoomDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoomDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RoomDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountryOfHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CountryOfHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountryOfHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CountryOfHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CityOfHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CityOfHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CityOfHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CityOfHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelsToCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet HotelsToCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelsToCity", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> HotelsToCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelsToCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet HotelsToCountry(string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelsToCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> HotelsToCountryAsync(string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelsDetailsAccordingToName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet HotelsDetailsAccordingToName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelsDetailsAccordingToName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> HotelsDetailsAccordingToNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookingDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BookingDetails(string ID, string FirstName, string LastName, string address, string country, string email, string mobile, string checkin, string checkout, string customerId, string hotelId, string roomId, string quantity, int total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookingDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BookingDetailsAsync(string ID, string FirstName, string LastName, string address, string country, string email, string mobile, string checkin, string checkout, string customerId, string hotelId, string roomId, string quantity, int total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Roomcount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Roomcount(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Roomcount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RoomcountAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookedRoomcount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int BookedRoomcount(string Checkin, string checkout, string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookedRoomcount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BookedRoomcountAsync(string Checkin, string checkout, string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoBookingID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoBookingID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoBookingID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoBookingIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyHotelsDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MyHotelsDetails(string hotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyHotelsDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MyHotelsDetailsAsync(string hotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyhotelBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MyhotelBooking(string hotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyhotelBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MyhotelBookingAsync(string hotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MyBooking(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MyBookingAsync(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Room", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Room(string RoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Room", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RoomAsync(string RoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelBooking(string bookingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CancelBookingAsync(string bookingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AllBooking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AllBookingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomertoID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CustomertoID(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomertoID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CustomertoIDAsync(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AdminUsername(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AdminUsernameAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HotelUsername(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HotelUsernameAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CustomerUsername(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CustomerUsernameAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Encrypt(string clearText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EncryptAsync(string clearText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoomDetailsbyHotelID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RoomDetailsbyHotelID(string HotelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoomDetailsbyHotelID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RoomDetailsbyHotelIDAsync(string HotelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHotel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteHotel(string HotelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteHotelAsync(string HotelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRoomByHotelId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteRoomByHotelId(string HotelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRoomByHotelId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteRoomByHotelIdAsync(string HotelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterDataHotel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FilterDataHotel(string data, string hotelid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterDataHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FilterDataHotelAsync(string data, string hotelid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterRoomTypeHotel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FilterRoomTypeHotel(string data, string hotelid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterRoomTypeHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FilterRoomTypeHotelAsync(string data, string hotelid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteRoom(string RoomID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteRoomAsync(string RoomID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateRoom(string RoomID, string Image, int quantity, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateRoomAsync(string RoomID, string Image, int quantity, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/customerDetailsbyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet customerDetailsbyID(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/customerDetailsbyID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> customerDetailsbyIDAsync(string customerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelsWebServiceSoapChannel : HotelWebClient.HotelServiceReference1.HotelsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelsWebServiceSoapClient : System.ServiceModel.ClientBase<HotelWebClient.HotelServiceReference1.HotelsWebServiceSoap>, HotelWebClient.HotelServiceReference1.HotelsWebServiceSoap {
        
        public HotelsWebServiceSoapClient() {
        }
        
        public HotelsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AutoID() {
            return base.Channel.AutoID();
        }
        
        public System.Threading.Tasks.Task<string> AutoIDAsync() {
            return base.Channel.AutoIDAsync();
        }
        
        public string insert(string ID, string Name, string Description, string No, string City, string Country, string mobile, string Email, string username, string password, string Image) {
            return base.Channel.insert(ID, Name, Description, No, City, Country, mobile, Email, username, password, Image);
        }
        
        public System.Threading.Tasks.Task<string> insertAsync(string ID, string Name, string Description, string No, string City, string Country, string mobile, string Email, string username, string password, string Image) {
            return base.Channel.insertAsync(ID, Name, Description, No, City, Country, mobile, Email, username, password, Image);
        }
        
        public string AutoCustomerID() {
            return base.Channel.AutoCustomerID();
        }
        
        public System.Threading.Tasks.Task<string> AutoCustomerIDAsync() {
            return base.Channel.AutoCustomerIDAsync();
        }
        
        public string AddCustomerData(string customerid, string fname, string lastname, string address, string gender, string bday, string mobile, string email, string uname, string pword) {
            return base.Channel.AddCustomerData(customerid, fname, lastname, address, gender, bday, mobile, email, uname, pword);
        }
        
        public System.Threading.Tasks.Task<string> AddCustomerDataAsync(string customerid, string fname, string lastname, string address, string gender, string bday, string mobile, string email, string uname, string pword) {
            return base.Channel.AddCustomerDataAsync(customerid, fname, lastname, address, gender, bday, mobile, email, uname, pword);
        }
        
        public System.Data.DataSet getHotelData() {
            return base.Channel.getHotelData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getHotelDataAsync() {
            return base.Channel.getHotelDataAsync();
        }
        
        public string AutoRoomID() {
            return base.Channel.AutoRoomID();
        }
        
        public System.Threading.Tasks.Task<string> AutoRoomIDAsync() {
            return base.Channel.AutoRoomIDAsync();
        }
        
        public string insertRoom(string ID, string Type, string Size, int price, int quantity, string Image, string hotelId) {
            return base.Channel.insertRoom(ID, Type, Size, price, quantity, Image, hotelId);
        }
        
        public System.Threading.Tasks.Task<string> insertRoomAsync(string ID, string Type, string Size, int price, int quantity, string Image, string hotelId) {
            return base.Channel.insertRoomAsync(ID, Type, Size, price, quantity, Image, hotelId);
        }
        
        public string HotelLoginData(string Username, string password) {
            return base.Channel.HotelLoginData(Username, password);
        }
        
        public System.Threading.Tasks.Task<string> HotelLoginDataAsync(string Username, string password) {
            return base.Channel.HotelLoginDataAsync(Username, password);
        }
        
        public string customerLoginData(string Username, string password) {
            return base.Channel.customerLoginData(Username, password);
        }
        
        public System.Threading.Tasks.Task<string> customerLoginDataAsync(string Username, string password) {
            return base.Channel.customerLoginDataAsync(Username, password);
        }
        
        public string AutoAdminID() {
            return base.Channel.AutoAdminID();
        }
        
        public System.Threading.Tasks.Task<string> AutoAdminIDAsync() {
            return base.Channel.AutoAdminIDAsync();
        }
        
        public string AddAdmin(string ID, string username, string pass) {
            return base.Channel.AddAdmin(ID, username, pass);
        }
        
        public System.Threading.Tasks.Task<string> AddAdminAsync(string ID, string username, string pass) {
            return base.Channel.AddAdminAsync(ID, username, pass);
        }
        
        public string AdminLoginData(string Username, string password) {
            return base.Channel.AdminLoginData(Username, password);
        }
        
        public System.Threading.Tasks.Task<string> AdminLoginDataAsync(string Username, string password) {
            return base.Channel.AdminLoginDataAsync(Username, password);
        }
        
        public System.Data.DataSet FilterData(string data) {
            return base.Channel.FilterData(data);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FilterDataAsync(string data) {
            return base.Channel.FilterDataAsync(data);
        }
        
        public System.Data.DataSet FilterRoomType(string data) {
            return base.Channel.FilterRoomType(data);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FilterRoomTypeAsync(string data) {
            return base.Channel.FilterRoomTypeAsync(data);
        }
        
        public System.Data.DataSet RoomDetails() {
            return base.Channel.RoomDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RoomDetailsAsync() {
            return base.Channel.RoomDetailsAsync();
        }
        
        public System.Data.DataSet CountryOfHotels() {
            return base.Channel.CountryOfHotels();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CountryOfHotelsAsync() {
            return base.Channel.CountryOfHotelsAsync();
        }
        
        public System.Data.DataSet CityOfHotels() {
            return base.Channel.CityOfHotels();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CityOfHotelsAsync() {
            return base.Channel.CityOfHotelsAsync();
        }
        
        public System.Data.DataSet HotelsToCity(string city) {
            return base.Channel.HotelsToCity(city);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> HotelsToCityAsync(string city) {
            return base.Channel.HotelsToCityAsync(city);
        }
        
        public System.Data.DataSet HotelsToCountry(string country) {
            return base.Channel.HotelsToCountry(country);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> HotelsToCountryAsync(string country) {
            return base.Channel.HotelsToCountryAsync(country);
        }
        
        public System.Data.DataSet HotelsDetailsAccordingToName(string name) {
            return base.Channel.HotelsDetailsAccordingToName(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> HotelsDetailsAccordingToNameAsync(string name) {
            return base.Channel.HotelsDetailsAccordingToNameAsync(name);
        }
        
        public string BookingDetails(string ID, string FirstName, string LastName, string address, string country, string email, string mobile, string checkin, string checkout, string customerId, string hotelId, string roomId, string quantity, int total) {
            return base.Channel.BookingDetails(ID, FirstName, LastName, address, country, email, mobile, checkin, checkout, customerId, hotelId, roomId, quantity, total);
        }
        
        public System.Threading.Tasks.Task<string> BookingDetailsAsync(string ID, string FirstName, string LastName, string address, string country, string email, string mobile, string checkin, string checkout, string customerId, string hotelId, string roomId, string quantity, int total) {
            return base.Channel.BookingDetailsAsync(ID, FirstName, LastName, address, country, email, mobile, checkin, checkout, customerId, hotelId, roomId, quantity, total);
        }
        
        public int Roomcount(string ID) {
            return base.Channel.Roomcount(ID);
        }
        
        public System.Threading.Tasks.Task<int> RoomcountAsync(string ID) {
            return base.Channel.RoomcountAsync(ID);
        }
        
        public int BookedRoomcount(string Checkin, string checkout, string Id) {
            return base.Channel.BookedRoomcount(Checkin, checkout, Id);
        }
        
        public System.Threading.Tasks.Task<int> BookedRoomcountAsync(string Checkin, string checkout, string Id) {
            return base.Channel.BookedRoomcountAsync(Checkin, checkout, Id);
        }
        
        public string AutoBookingID() {
            return base.Channel.AutoBookingID();
        }
        
        public System.Threading.Tasks.Task<string> AutoBookingIDAsync() {
            return base.Channel.AutoBookingIDAsync();
        }
        
        public System.Data.DataSet MyHotelsDetails(string hotelId) {
            return base.Channel.MyHotelsDetails(hotelId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MyHotelsDetailsAsync(string hotelId) {
            return base.Channel.MyHotelsDetailsAsync(hotelId);
        }
        
        public System.Data.DataSet MyhotelBooking(string hotelId) {
            return base.Channel.MyhotelBooking(hotelId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MyhotelBookingAsync(string hotelId) {
            return base.Channel.MyhotelBookingAsync(hotelId);
        }
        
        public System.Data.DataSet MyBooking(string customerId) {
            return base.Channel.MyBooking(customerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MyBookingAsync(string customerId) {
            return base.Channel.MyBookingAsync(customerId);
        }
        
        public System.Data.DataSet Room(string RoomId) {
            return base.Channel.Room(RoomId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RoomAsync(string RoomId) {
            return base.Channel.RoomAsync(RoomId);
        }
        
        public string CancelBooking(string bookingID) {
            return base.Channel.CancelBooking(bookingID);
        }
        
        public System.Threading.Tasks.Task<string> CancelBookingAsync(string bookingID) {
            return base.Channel.CancelBookingAsync(bookingID);
        }
        
        public System.Data.DataSet AllBooking() {
            return base.Channel.AllBooking();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AllBookingAsync() {
            return base.Channel.AllBookingAsync();
        }
        
        public System.Data.DataSet CustomertoID(string customerId) {
            return base.Channel.CustomertoID(customerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CustomertoIDAsync(string customerId) {
            return base.Channel.CustomertoIDAsync(customerId);
        }
        
        public string AdminUsername(string Username) {
            return base.Channel.AdminUsername(Username);
        }
        
        public System.Threading.Tasks.Task<string> AdminUsernameAsync(string Username) {
            return base.Channel.AdminUsernameAsync(Username);
        }
        
        public string HotelUsername(string Username) {
            return base.Channel.HotelUsername(Username);
        }
        
        public System.Threading.Tasks.Task<string> HotelUsernameAsync(string Username) {
            return base.Channel.HotelUsernameAsync(Username);
        }
        
        public string CustomerUsername(string Username) {
            return base.Channel.CustomerUsername(Username);
        }
        
        public System.Threading.Tasks.Task<string> CustomerUsernameAsync(string Username) {
            return base.Channel.CustomerUsernameAsync(Username);
        }
        
        public string Encrypt(string clearText) {
            return base.Channel.Encrypt(clearText);
        }
        
        public System.Threading.Tasks.Task<string> EncryptAsync(string clearText) {
            return base.Channel.EncryptAsync(clearText);
        }
        
        public System.Data.DataSet RoomDetailsbyHotelID(string HotelID) {
            return base.Channel.RoomDetailsbyHotelID(HotelID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RoomDetailsbyHotelIDAsync(string HotelID) {
            return base.Channel.RoomDetailsbyHotelIDAsync(HotelID);
        }
        
        public string DeleteHotel(string HotelID) {
            return base.Channel.DeleteHotel(HotelID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteHotelAsync(string HotelID) {
            return base.Channel.DeleteHotelAsync(HotelID);
        }
        
        public string DeleteRoomByHotelId(string HotelID) {
            return base.Channel.DeleteRoomByHotelId(HotelID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRoomByHotelIdAsync(string HotelID) {
            return base.Channel.DeleteRoomByHotelIdAsync(HotelID);
        }
        
        public System.Data.DataSet FilterDataHotel(string data, string hotelid) {
            return base.Channel.FilterDataHotel(data, hotelid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FilterDataHotelAsync(string data, string hotelid) {
            return base.Channel.FilterDataHotelAsync(data, hotelid);
        }
        
        public System.Data.DataSet FilterRoomTypeHotel(string data, string hotelid) {
            return base.Channel.FilterRoomTypeHotel(data, hotelid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FilterRoomTypeHotelAsync(string data, string hotelid) {
            return base.Channel.FilterRoomTypeHotelAsync(data, hotelid);
        }
        
        public string DeleteRoom(string RoomID) {
            return base.Channel.DeleteRoom(RoomID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRoomAsync(string RoomID) {
            return base.Channel.DeleteRoomAsync(RoomID);
        }
        
        public string UpdateRoom(string RoomID, string Image, int quantity, int price) {
            return base.Channel.UpdateRoom(RoomID, Image, quantity, price);
        }
        
        public System.Threading.Tasks.Task<string> UpdateRoomAsync(string RoomID, string Image, int quantity, int price) {
            return base.Channel.UpdateRoomAsync(RoomID, Image, quantity, price);
        }
        
        public System.Data.DataSet customerDetailsbyID(string customerID) {
            return base.Channel.customerDetailsbyID(customerID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> customerDetailsbyIDAsync(string customerID) {
            return base.Channel.customerDetailsbyIDAsync(customerID);
        }
    }
}
